/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.115
 * Generated at: 2026-04-22 22:08:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import classes.MedicamentoDAO;
import classes.Medicamento;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/joaop/.m2/repository/javax/servlet/jstl/1.2/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153395882000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1773270668897L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("classes.Medicamento");
    _jspx_imports_classes.add("classes.MedicamentoDAO");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fimport_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");

    // Recupera a lista enviada pela Servlet (busca)
    List<Medicamento> lista = (List<Medicamento>) request.getAttribute("lista");

    // Se a lista for nula (acesso direto à home), carrega os produtos pre-setados do DAO
    if(lista == null){
        lista = MedicamentoDAO.listar();
    }

    String termoBusca = (String) request.getAttribute("busca");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<main class=\"container my-5 min-vh-100\">\r\n");
      out.write("\r\n");
      out.write("    <div class=\"row mb-5 align-items-center\">\r\n");
      out.write("        <div class=\"col-md-7\">\r\n");
      out.write("            <h2 class=\"fw-bold\" style=\"color: #0c795a;\">\r\n");
      out.write("                <i class=\"bi text-warning me-2\"></i>\r\n");
      out.write("                ");
      out.print( (termoBusca != null) ? "Resultados para: " + termoBusca : "Medicamentos em Destaque" );
      out.write("\r\n");
      out.write("            </h2>\r\n");
      out.write("            <p class=\"text-muted lead\">\r\n");
      out.write("                ");
      out.print( (termoBusca != null) ? "Encontramos " + lista.size() + " item(ns) para sua pesquisa." : "Confira os itens em promoção e os últimos lançamentos do nosso estoque." );
      out.write("\r\n");
      out.write("            </p>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-md-5 text-md-end\">\r\n");
      out.write("            <a href=\"medicamento?acao=listar\" class=\"btn btn-outline-success rounded-pill px-4 fw-bold\">\r\n");
      out.write("                <i class=\"bi bi-grid-3x3-gap me-2\"></i>Ver Painel Geral\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"row row-cols-1 row-cols-md-2 row-cols-lg-3 g-4\">\r\n");
      out.write("\r\n");
      out.write("        ");

            if(lista != null && !lista.isEmpty()){
                for(Medicamento m : lista){

                    // Se o medicamento está vencido E o usuário NÃO está logado, pula para o próximo da lista
                    if(m.isVencido() && session.getAttribute("usuario") == null) {
                        continue;
                    }

        
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col\">\r\n");
      out.write("            <div class=\"card h-100 border-0 shadow-sm custom-card\">\r\n");
      out.write("\r\n");
      out.write("                ");
 if(m.isVencido()) { 
      out.write("\r\n");
      out.write("                    <div class=\"card-badge bg-danger text-white px-3 py-1 fw-bold\">VENCIDO</div>\r\n");
      out.write("                ");
 } else if(m.isPromocao()) { 
      out.write("\r\n");
      out.write("                    <div class=\"card-badge bg-warning text-dark px-3 py-1 fw-bold\">PROMOÇÃO</div>\r\n");
      out.write("                ");
 } else { 
      out.write("\r\n");
      out.write("                    <div class=\"card-badge bg-info text-white px-3 py-1 fw-bold\">NOVO</div>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <div class=\"card-body p-4 text-center\">\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"mb-3\">\r\n");
      out.write("                        ");
 if(m.getForma().equalsIgnoreCase("Solução") || m.getForma().equalsIgnoreCase("Injetável")) { 
      out.write("\r\n");
      out.write("                            <i class=\"bi bi-droplet-half text-primary\" style=\"font-size: 3.5rem;\"></i>\r\n");
      out.write("                        ");
 } else { 
      out.write("\r\n");
      out.write("                            <i class=\"bi bi-capsule text-success\" style=\"font-size: 3.5rem;\"></i>\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <h5 class=\"card-title fw-bold text-dark mb-1\">\r\n");
      out.write("                        ");
      out.print( m.getNome() );
      out.write("\r\n");
      out.write("                    </h5>\r\n");
      out.write("\r\n");
      out.write("                    <p class=\"text-muted small mb-3\">\r\n");
      out.write("                        ");
      out.print( m.getPrincipioAtivo() );
      out.write("\r\n");
      out.write("                    </p>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"d-flex justify-content-center gap-2 mb-4\">\r\n");
      out.write("                        <span class=\"badge rounded-pill text-success\" style=\"background-color: #D8F3DC; font-size: 0.85rem;\">\r\n");
      out.write("                            ");
      out.print( m.getForma() );
      out.write("\r\n");
      out.write("                        </span>\r\n");
      out.write("                        <span class=\"badge rounded-pill text-secondary bg-light border\" style=\"font-size: 0.85rem;\">\r\n");
      out.write("                            Lote: ");
      out.print( m.getLote() );
      out.write("\r\n");
      out.write("                        </span>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <ul class=\"list-unstyled text-start small mb-4 p-3 rounded-3\" style=\"background-color: #f8f9fa;\">\r\n");
      out.write("                        <li class=\"mb-2\">\r\n");
      out.write("                            <i class=\"bi bi-building text-success me-2\"></i>\r\n");
      out.write("                            <strong>Fabricante:</strong> ");
      out.print( m.getFabricante() );
      out.write("\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <i class=\"bi bi-calendar-check text-success me-2\"></i>\r\n");
      out.write("                            <strong>Validade:</strong>\r\n");
      out.write("                            <span class=\"");
      out.print( m.isVencido() ? "text-danger fw-bold" : "" );
      out.write("\">\r\n");
      out.write("                                ");
      out.print( m.getValidadeFormatada() );
      out.write("\r\n");
      out.write("                            </span>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("\r\n");
      out.write("                    <a href=\"medicamento?acao=detalhes&id=");
      out.print(m.getId());
      out.write("\"\r\n");
      out.write("                       class=\"btn btn-primary-custom w-100 py-2 rounded-pill fw-bold shadow-sm\">\r\n");
      out.write("                        Ver Detalhes Técnicos\r\n");
      out.write("                    </a>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        ");

            }
        } else {
        
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-12 text-center py-5\">\r\n");
      out.write("            <i class=\"bi bi-search text-muted\" style=\"font-size: 4rem;\"></i>\r\n");
      out.write("            <h4 class=\"mt-4 text-muted\">Nenhum medicamento encontrado</h4>\r\n");
      out.write("            <p class=\"text-muted\">Tente buscar por outro termo ou cadastre novos itens no painel.</p>\r\n");
      out.write("            <a href=\"index.jsp\" class=\"btn btn-success rounded-pill mt-3\">Limpar Busca</a>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        ");

            }
        
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</main>\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fimport_005f1(_jspx_page_context))
        return;
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fimport_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f0 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    try {
      _jspx_th_c_005fimport_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f0.setParent(null);
      // /index.jsp(5,0) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f0.setUrl("/includes/header.jsp");
      int[] _jspx_push_body_count_c_005fimport_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f0 = _jspx_th_c_005fimport_005f0.doStartTag();
        if (_jspx_th_c_005fimport_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f0.doFinally();
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fimport_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f1 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    try {
      _jspx_th_c_005fimport_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f1.setParent(null);
      // /index.jsp(132,0) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f1.setUrl("/includes/footer.jsp");
      int[] _jspx_push_body_count_c_005fimport_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f1 = _jspx_th_c_005fimport_005f1.doStartTag();
        if (_jspx_th_c_005fimport_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f1.doFinally();
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f1);
    }
    return false;
  }
}
