/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.115
 * Generated at: 2026-04-20 18:08:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.includes;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class footer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("  <footer class=\"custom-footer mt-5\">\r\n");
      out.write("            <div class=\"container py-5\">\r\n");
      out.write("                <div class=\"row g-4\">\r\n");
      out.write("                    <!-- Coluna 1: Sobre / Logo -->\r\n");
      out.write("                    <div class=\"col-lg-4 col-md-6\">\r\n");
      out.write("\r\n");
      out.write("                        <h5 class=\"fw-bold mb-3 text-white\"><br><i class=\"bi bi-capsule-pill me-2\"></i>Fármacos & Cia</h5>\r\n");
      out.write("                        <p class=\"text-footer-muted\">\r\n");
      out.write("                            Sistema de gerenciamento farmacêutico dedicado à organização, \r\n");
      out.write("                            segurança e controle de medicamentos para profissionais da saúde.\r\n");
      out.write("                        </p>\r\n");
      out.write("                        <div class=\"social-links d-flex gap-3\">\r\n");
      out.write("                            <a href=\"#\"><i class=\"bi bi-instagram\"></i></a>\r\n");
      out.write("                            <a href=\"#\"><i class=\"bi bi-facebook\"></i></a>\r\n");
      out.write("                            <a href=\"https://github.com/Jaooow/Projeto-ARQWEB1\"><i class=\"bi bi-github\"></i></a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- Coluna 2: Links Rápidos -->\r\n");
      out.write("                    <div class=\"col-lg-2 col-md-6\">\r\n");
      out.write("                        <h6 class=\"text-white fw-bold mb-3\">Navegação</h6>\r\n");
      out.write("                        <ul class=\"list-unstyled footer-links\">\r\n");
      out.write("                            <li><a href=\"#\">Home</a></li>\r\n");
      out.write("                            <li><a href=\"#\">Sobre o Sistema</a></li>\r\n");
      out.write("                            <li><a href=\"#\">Medicamentos</a></li>\r\n");
      out.write("                            <li><a href=\"#\">Relatórios</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- Coluna 3: Suporte/Privacidade -->\r\n");
      out.write("                    <div class=\"col-lg-2 col-md-6\">\r\n");
      out.write("                        <h6 class=\"text-white fw-bold mb-3\">Suporte</h6>\r\n");
      out.write("                        <ul class=\"list-unstyled footer-links\">\r\n");
      out.write("                            <li><a href=\"#\">Ajuda</a></li>\r\n");
      out.write("                            <li><a href=\"#\">Privacidade</a></li>\r\n");
      out.write("                            <li><a href=\"#\">Termos de Uso</a></li>\r\n");
      out.write("                            <li><a href=\"#\">Contato</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                   <!-- Contato -->\r\n");
      out.write("                    <div class=\"col-lg-4 col-md-6\">\r\n");
      out.write("                        <h6 class=\"text-white fw-bold mb-3\">Atendimento</h6>\r\n");
      out.write("                        <ul class=\"list-unstyled\">\r\n");
      out.write("                            <li class=\"mb-2\">\r\n");
      out.write("                                <i class=\"bi bi-geo-alt\"></i>\r\n");
      out.write("                                <span>Av. das Farmácias, 123 - Centro</span>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"mb-2\">\r\n");
      out.write("                                <i class=\"bi bi-envelope\"></i>\r\n");
      out.write("                                <span>suporte@farmacos.com.br</span>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"mb-2\">\r\n");
      out.write("                                <i class=\"bi bi-telephone\"></i>\r\n");
      out.write("                                <span>(11) 4002-8922</span>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Barra de Direitos Autorais -->\r\n");
      out.write("            <div class=\"footer-bottom py-3\">\r\n");
      out.write("                <div class=\"container text-center\">\r\n");
      out.write("                    <p class=\"mb-0 text-footer-muted small\">\r\n");
      out.write("                        &copy; 2026 Fármacos & Cia. Todos os direitos reservados. \r\n");
      out.write("                        <span class=\"d-block d-md-inline\">Desenvolvido por <strong>João Pedro & Marcus</strong></span>\r\n");
      out.write("                    </p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </footer>\r\n");
      out.write("\r\n");
      out.write("        <!-- Modal de Login -->\r\n");
      out.write("        <div class=\"modal fade\" id=\"loginModal\" tabindex=\"-1\">\r\n");
      out.write("            <div class=\"modal-dialog modal-dialog-centered\">\r\n");
      out.write("                <div class=\"modal-content border-0 shadow-lg\">\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"modal-header text-white\" style=\"background-color: #2D6A4F;\">\r\n");
      out.write("                        <h5 class=\"modal-title fw-bold\">\r\n");
      out.write("                            <i class=\"bi bi-lock-fill me-2\"></i>Acesso Restrito\r\n");
      out.write("                        </h5>\r\n");
      out.write("                        <button type=\"button\" class=\"btn-close btn-close-white\" data-bs-dismiss=\"modal\"></button>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"modal-body p-4\">\r\n");
      out.write("\r\n");
      out.write("                        <!-- ACTION -->\r\n");
      out.write("                        <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/login\" method=\"POST\">\r\n");
      out.write("                            <!-- USUÁRIO -->\r\n");
      out.write("                            <div class=\"mb-3\">\r\n");
      out.write("                                <label class=\"form-label fw-semibold\" style=\"color: #2D6A4F;\">Usuário</label>\r\n");
      out.write("                                <div class=\"input-group\">\r\n");
      out.write("                                    <span class=\"input-group-text bg-light border-end-0\">\r\n");
      out.write("                                        <i class=\"bi bi-person text-muted\"></i>\r\n");
      out.write("                                    </span>\r\n");
      out.write("\r\n");
      out.write("                                    <input type=\"text\" name=\"login\"\r\n");
      out.write("                                           class=\"form-control border-start-0 bg-light\"\r\n");
      out.write("                                           placeholder=\"Digite seu usuário\" required>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <!-- SENHA -->\r\n");
      out.write("                            <div class=\"mb-4\">\r\n");
      out.write("                                <label class=\"form-label fw-semibold\" style=\"color: #2D6A4F;\">Senha</label>\r\n");
      out.write("                                <div class=\"input-group\">\r\n");
      out.write("                                    <span class=\"input-group-text bg-light border-end-0\">\r\n");
      out.write("                                        <i class=\"bi bi-key text-muted\"></i>\r\n");
      out.write("                                    </span>\r\n");
      out.write("\r\n");
      out.write("                                    <input type=\"password\" name=\"senha\"\r\n");
      out.write("                                           class=\"form-control border-start-0 bg-light\"\r\n");
      out.write("                                           placeholder=\"Digite sua senha\" required>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <button type=\"submit\"\r\n");
      out.write("                                    class=\"btn w-100 fw-bold py-2 shadow-sm\"\r\n");
      out.write("                                    style=\"background-color: #2D6A4F; color: white;\">\r\n");
      out.write("                                Entrar no Sistema\r\n");
      out.write("                            </button>\r\n");
      out.write("\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"modal-footer justify-content-center border-0 bg-light\">\r\n");
      out.write("                        <small class=\"text-muted\">\r\n");
      out.write("                            Esqueceu sua senha?\r\n");
      out.write("                            <a href=\"#\" class=\"text-decoration-none\" style=\"color: #2D6A4F;\">\r\n");
      out.write("                                Clique aqui\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </small>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js\" integrity=\"sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.min.js\" integrity=\"sha384-G/EV+4j2dNv+tEPo3++6LCgdCROaejBqfUeNjuKAiuXbjrxilcCdDz6ZAVfHWe1Y\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("    </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
